import type { SystemBlock } from "@/lib/ai/providers/types";
import type { ChunkRecord, SourceRecord, WorkspaceRecord } from "@/lib/db/types";
import type {
  PodcastChapter,
  PodcastSegment,
  PodcastSourceRef,
  PodcastSpeaker,
} from "@/lib/podcast/types";

// Bump this string when the prompt or schema changes so persisted
// records can later be filtered/regenerated by prompt version.
export const PODCAST_SCRIPT_PROMPT_VERSION = "podcast-script@1";

export type PodcastPromptInput = {
  workspace: Pick<WorkspaceRecord, "name" | "goal">;
  sources: Array<
    Pick<SourceRecord, "id" | "title" | "titleEn" | "type" | "author"> & {
      chunks: Array<
        Pick<ChunkRecord, "id" | "index" | "section" | "headings" | "text" | "page">
      >;
    }
  >;
  locale: "tr" | "en";
  /** Approximate finished-podcast length in minutes (5–60). Drives the
   *  recommended segment count the model is asked to hit; final length
   *  is governed by TTS in 5.B.B, not by this prompt. */
  durationMin?: number | undefined;
  /** Host display names — surface in the prompt so the model addresses
   *  them by name rather than fixed strings. Defaults to Alev / Deniz. */
  hosts?: {
    alev: string;
    deniz: string;
  } | undefined;
};

export type ParsedPodcastSegment = {
  speaker: PodcastSpeaker;
  text: string;
  sourceRefs: PodcastSourceRef[];
};

export type ParsedPodcastChapter = Pick<PodcastChapter, "title" | "segmentIndex">;

export type ParsedPodcast = {
  title: string;
  titleEn?: string | undefined;
  description?: string | undefined;
  chapters: ParsedPodcastChapter[];
  segments: ParsedPodcastSegment[];
};

const DEFAULT_DURATION_MIN = 20;
// ~150 words per minute spoken, ~12 words per turn average → 12.5 turns/min.
// We slightly under-target so the model leaves room for chapter beats.
const TURNS_PER_MIN = 11;
const MIN_TURNS = 16;
const MAX_TURNS = 240;

const HOST_DEFAULTS = { alev: "Alev", deniz: "Deniz" } as const;

function clampDuration(min: number | undefined): number {
  if (typeof min !== "number" || !Number.isFinite(min)) return DEFAULT_DURATION_MIN;
  return Math.max(5, Math.min(60, Math.round(min)));
}

function targetTurns(durationMin: number): number {
  const raw = Math.round(durationMin * TURNS_PER_MIN);
  return Math.max(MIN_TURNS, Math.min(MAX_TURNS, raw));
}

const RULES_EN = (turns: number, hosts: { alev: string; deniz: string }): string =>
  [
    `Role: You are a podcast script-writer producing a two-host dialogue between ${hosts.alev} (the curious learner) and ${hosts.deniz} (the expert).`,
    `Task: Produce a grounded ~${turns}-turn conversation that teaches the workspace topic using ONLY the supplied <workspace_sources>.`,
    "Rules:",
    "- Speakers strictly alternate roles: `alev` asks, reflects, or pushes back; `deniz` explains, gives examples, and corrects misconceptions.",
    `- Speaker ids are exactly the lowercase tokens \`alev\` and \`deniz\`. Do NOT use display names (${hosts.alev} / ${hosts.deniz}) in the speaker field.`,
    "- Open with a 1–2 turn cold-open hook (no formal greetings), then move into chapters.",
    "- Each `chapters[i].segmentIndex` must be an integer pointing at the FIRST segment of that chapter (0-indexed into `segments`).",
    "- Provide 3–6 chapters, each with a short Turkish/English neutral title (max 60 chars).",
    "- Ground claims in <workspace_sources>; cite chunk ids in `sourceRefs[].chunkIds` when a claim depends on a source passage.",
    "- Avoid filler turns (\"right\", \"yeah\"); every turn should carry information, contrast, an example, or a question.",
    "- Do NOT invent facts beyond the sources; if a topic is unsupported, have one host flag the gap instead of fabricating.",
    "- Output ONLY the JSON object below. No markdown fences, no commentary, no preamble.",
  ].join("\n");

const RULES_TR = (turns: number, hosts: { alev: string; deniz: string }): string =>
  [
    `Rol: ${hosts.alev} (meraklı öğrenen) ile ${hosts.deniz} (uzman) arasında geçen iki sunuculu bir podcast diyaloğu yazan bir senaryo yazarısın.`,
    `Görev: Yalnızca <workspace_sources> kapsamındaki bilgiyi kullanarak konuyu öğreten ~${turns} replikli bir konuşma üret.`,
    "Kurallar:",
    "- Konuşmacılar rolleri dönüşümlü kullanır: `alev` sorar, yansıtır, itiraz eder; `deniz` açıklar, örnek verir, yanlış anlamaları düzeltir.",
    `- Konuşmacı id'leri tam olarak küçük harfli \`alev\` ve \`deniz\`'dir. Görünen isimleri (${hosts.alev} / ${hosts.deniz}) speaker alanında KULLANMA.`,
    "- 1–2 repliklik kısa bir cold-open ile başla (resmi selamlamalar yok), sonra bölümlere geç.",
    "- Her `chapters[i].segmentIndex` bölümün İLK segmentinin indeksi olmalı (0-indeksli, `segments` dizisine).",
    "- 3–6 bölüm üret, her bölümün başlığı kısa olsun (en fazla 60 karakter).",
    "- İddialarını <workspace_sources>'a dayandır; kaynağa dayanan iddialar için `sourceRefs[].chunkIds` ile chunk id'leri ver.",
    "- Doldurma replikler ekleme (\"evet\", \"tabii\"); her replik bilgi, karşıtlık, örnek veya soru taşımalı.",
    "- Kaynak dışı bilgi uydurma; bir konu kaynaklarda yoksa, sunuculardan biri bu eksikliği belirtmeli.",
    "- SADECE aşağıdaki JSON objesini üret. Markdown fence, açıklama veya önsöz ekleme.",
  ].join("\n");

const SCHEMA = [
  "{",
  '  "title": "string",',
  '  "titleEn": "string (optional English title — omit if locale=en)",',
  '  "description": "string (1–2 sentence hook)",',
  '  "chapters": [',
  '    { "title": "string", "segmentIndex": 0 }',
  "  ],",
  '  "segments": [',
  "    {",
  '      "speaker": "alev | deniz",',
  '      "text": "string (one spoken turn — 1–4 sentences)",',
  '      "sourceRefs": [{ "sourceId": "src_id", "chunkIds": ["ck_id"], "section": "string", "quote": "string" }]',
  "    }",
  "  ]",
  "}",
].join("\n");

export function buildPodcastScriptSystem(
  input: PodcastPromptInput,
): SystemBlock[] {
  const durationMin = clampDuration(input.durationMin);
  const turns = targetTurns(durationMin);
  const hosts = input.hosts ?? HOST_DEFAULTS;
  const rules =
    input.locale === "tr" ? RULES_TR(turns, hosts) : RULES_EN(turns, hosts);
  const goal = input.workspace.goal
    ? ` goal=${JSON.stringify(input.workspace.goal)}`
    : "";
  const sourceBlocks = input.sources.map((source) => {
    const author = source.author
      ? ` author=${JSON.stringify(source.author)}`
      : "";
    const chunks = source.chunks.map((chunk) => {
      const bits = [`#${chunk.index}`, `id=${chunk.id}`];
      if (chunk.section) bits.push(`section: ${chunk.section}`);
      else if (chunk.headings?.[0]) bits.push(`section: ${chunk.headings[0]}`);
      if (typeof chunk.page === "number") bits.push(`page: ${chunk.page}`);
      return `---chunk ${bits.join(" · ")}---\n${chunk.text}`;
    });
    return [
      `<source id=${JSON.stringify(source.id)} title=${JSON.stringify(source.titleEn ?? source.title)} type=${JSON.stringify(source.type)}${author}>`,
      ...chunks,
      "</source>",
    ].join("\n\n");
  });
  const payload = [
    `<workspace_sources workspace=${JSON.stringify(input.workspace.name)}${goal} duration_min=${durationMin}>`,
    ...sourceBlocks,
    "</workspace_sources>",
  ].join("\n\n");

  return [
    { type: "text", text: `${rules}\n\nSchema:\n${SCHEMA}` },
    {
      type: "text",
      text: payload,
      cache_control: { type: "ephemeral" },
    },
  ];
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed.startsWith("```")) return trimmed;
  return trimmed
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const item of value) {
    const str = asString(item);
    if (str) out.push(str);
  }
  return out;
}

function asSpeaker(value: unknown): PodcastSpeaker | undefined {
  if (typeof value !== "string") return undefined;
  const lower = value.trim().toLowerCase();
  if (lower === "alev" || lower === "deniz") return lower;
  return undefined;
}

function parseSourceRefs(value: unknown): PodcastSourceRef[] {
  if (!Array.isArray(value)) return [];
  const refs: PodcastSourceRef[] = [];
  for (const item of value) {
    if (!isPlainObject(item)) continue;
    const sourceId = asString(item.sourceId);
    if (!sourceId) continue;
    const ref: PodcastSourceRef = { sourceId };
    const chunkIds = asStringArray(item.chunkIds);
    if (chunkIds.length > 0) ref.chunkIds = chunkIds;
    const section = asString(item.section);
    if (section) ref.section = section;
    const quote = asString(item.quote);
    if (quote) ref.quote = quote;
    refs.push(ref);
  }
  return refs;
}

function parseChapters(
  raw: unknown,
  segmentCount: number,
): ParsedPodcastChapter[] {
  if (!Array.isArray(raw)) return [];
  const out: ParsedPodcastChapter[] = [];
  for (const item of raw) {
    if (!isPlainObject(item)) continue;
    const title = asString(item.title);
    if (!title) continue;
    const rawIndex = item.segmentIndex;
    let segmentIndex = 0;
    if (typeof rawIndex === "number" && Number.isFinite(rawIndex)) {
      segmentIndex = Math.max(0, Math.min(segmentCount - 1, Math.floor(rawIndex)));
    }
    out.push({ title, segmentIndex });
  }
  // De-dup adjacent chapters that land on the same segment so the
  // transcript view doesn't render two boundaries on top of each other.
  const deduped: ParsedPodcastChapter[] = [];
  for (const ch of out) {
    const last = deduped[deduped.length - 1];
    if (last && last.segmentIndex === ch.segmentIndex) continue;
    deduped.push(ch);
  }
  return deduped;
}

export function parsePodcastScript(raw: string): ParsedPodcast {
  const cleaned = stripCodeFence(raw);
  const firstBrace = cleaned.indexOf("{");
  if (firstBrace === -1) {
    throw new Error("podcast-script: no JSON object found in response");
  }
  const jsonText = cleaned.slice(firstBrace);
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonText);
  } catch {
    const lastBrace = jsonText.lastIndexOf("}");
    if (lastBrace === -1) {
      throw new Error("podcast-script: response is not valid JSON");
    }
    parsed = JSON.parse(jsonText.slice(0, lastBrace + 1));
  }
  if (!isPlainObject(parsed)) {
    throw new Error("podcast-script: response is not an object");
  }

  const title = asString(parsed.title) ?? "Podcast";
  const titleEn = asString(parsed.titleEn);
  const description = asString(parsed.description);

  const rawSegments = Array.isArray(parsed.segments) ? parsed.segments : [];
  const segments: ParsedPodcastSegment[] = [];
  for (const rawSegment of rawSegments) {
    if (!isPlainObject(rawSegment)) continue;
    const speaker = asSpeaker(rawSegment.speaker);
    const text = asString(rawSegment.text);
    if (!speaker || !text) continue;
    segments.push({
      speaker,
      text,
      sourceRefs: parseSourceRefs(rawSegment.sourceRefs),
    });
  }

  if (segments.length === 0) {
    throw new Error("podcast-script: no valid segments in response");
  }

  const chapters = parseChapters(parsed.chapters, segments.length);
  // Always guarantee a first chapter so the transcript view has a head
  // anchor even when the model omitted chapters entirely.
  if (chapters.length === 0) {
    chapters.push({ title, segmentIndex: 0 });
  } else if (chapters[0] && chapters[0].segmentIndex !== 0) {
    chapters.unshift({ title, segmentIndex: 0 });
  }

  const result: ParsedPodcast = {
    title,
    chapters,
    segments,
  };
  if (titleEn) result.titleEn = titleEn;
  if (description) result.description = description;
  return result;
}
