// Roadmap feature — locked design 2026-05-25 (docs/ROADMAP_FEATURE_SPEC.md).
// Replaces the calendar-based Plan feature. A Roadmap is a prerequisite-DAG
// of learning topics generated by AI as a single JSON shot. Nodes are nested
// to a maximum depth of 2 (root → child → grandchild) so the force-sim
// canvas and token budget both stay bounded.
//
// Types live outside src/lib/db/types.ts because the rest of the feature
// (AI runner, layout, components) reads from this module too — keeping the
// canonical shape next to the feature folder mirrors the concepts/types.ts
// pattern Phase 4.E established for the Mind Map graph.

export type RoadmapTimeframe = "daily" | "weekly" | "monthly";

export type RoadmapLevel = "beginner" | "intermediate" | "advanced";

// Output-language choice captured per roadmap at generation time.
//   tr           → all content Turkish
//   en           → all content English
//   en_terms_tr  → Turkish explanations, technical terms kept in English
//   both         → content generated in one language + translated into the
//                  other; stored in parallel `*En` fields so the graph view
//                  can flip TR⇄EN instantly with no re-generation.
// Optional on records so legacy roadmaps (created before this feature) read
// back as "no declared mode" = single-language, no toggle.
export type RoadmapLangMode = "tr" | "en" | "en_terms_tr" | "both";

export type RoadmapNodeStatus = "todo" | "done";

// Depth bucket — root is 0, the AI-generated subtask call promotes children
// to depth 1, and a second "Create subtasks" call promotes grandchildren to
// depth 2. The Create-subtasks button is hard-disabled at depth 2 so we
// never produce a fourth level (see `MAX_ROADMAP_DEPTH`).
export type RoadmapNodeDepth = 0 | 1 | 2;

export const MAX_ROADMAP_DEPTH: RoadmapNodeDepth = 2;

export type RoadmapRecord = {
  id: string;
  workspaceId: string;
  title: string;
  // English title, populated only for `langMode: "both"`. The graph view picks
  // `title` vs `titleEn` from the local TR/EN toggle.
  titleEn?: string | undefined;
  // The language mode chosen in the wizard. Undefined on legacy roadmaps =
  // single-language, no toggle shown.
  langMode?: RoadmapLangMode | undefined;
  // Free-form user prompt that generated the roadmap. Kept verbatim so the
  // wizard can prefill on "Re-generate" later and the node-budget chip can
  // explain why the graph has the size it does.
  topic: string;
  timeframe: RoadmapTimeframe;
  level: RoadmapLevel;
  // Optional learner goal collected in wizard step 3 ("Roadmap sonunda ne
  // yapabilmek istiyorsun?"). Forwarded into the AI prompt verbatim.
  goal?: string | undefined;
  // Mirrors the state of the "Workspace kaynaklarını kullan" switch at
  // creation time. We surface it on the card so the user knows whether the
  // graph was source-grounded vs topic-only generic.
  usedSources: boolean;
  // Model literal as written to chatMessages.model in the rest of the app
  // (e.g. "claude-sonnet-4-6"). Kept on the row so cost reports can roll up
  // by model and the inspector can show provenance.
  model: string;
  createdAt: number;
  updatedAt: number;
};

export type RoadmapNodeRecord = {
  id: string;
  roadmapId: string;
  // `null` (not undefined) for root nodes so the compound
  // `[roadmapId+parentId]` index has a stable bucket for "every root node in
  // this roadmap". Dexie's where-clause on `null` is well-defined; on
  // `undefined` it would silently miss rows.
  parentId: string | null;
  depth: RoadmapNodeDepth;
  title: string;
  description: string;
  // English variants, populated only for `langMode: "both"` roadmaps. The
  // canvas/inspector render `titleEn`/`descriptionEn` when the view toggle is
  // on EN, falling back to the base field when a translation is missing.
  titleEn?: string | undefined;
  descriptionEn?: string | undefined;
  status: RoadmapNodeStatus;
  // Cached canvas position. Written when the user drags a node (see `pinned`);
  // the auto layered layout otherwise leaves these undefined. Not indexed.
  x?: number | undefined;
  y?: number | undefined;
  // True once the user has manually dragged this node on the canvas. A pinned
  // node keeps its cached x/y and is skipped by the auto layered layout, so a
  // hand-arranged graph survives reload. "Düzeni sıfırla" clears the flag.
  pinned?: boolean | undefined;
  // Links to entities spawned from this node so it stops being a dead-end
  // string: a "Study as note" note + a generated flashcard deck. Not indexed
  // — progress aggregation scans the bounded per-roadmap node set.
  noteId?: string | undefined;
  deckId?: string | undefined;
  createdAt: number;
  updatedAt: number;
};

export type RoadmapEdgeRecord = {
  id: string;
  roadmapId: string;
  // Directed: `fromNode` is the prerequisite of `toNode`. Renderer draws an
  // arrowhead at `toNode`.
  fromNodeId: string;
  toNodeId: string;
  createdAt: number;
};
